bcftools: /projects/scarball/apps/Modules/software/bcftools/1.16/bin/bcftools
call_parameters:
  baq: partial # bcftools BAQ setting to use, "with", "without", or "partial" (recommended)
  block_size: 5000000 # Block size for scatter/gather calling
  bq: 30 # minimum base quality
  mq: 30 # minimum mapping quality
  size_cutoff: 100000 # Minimum size of contigs for calls
plink: /opt/software/plink/1.9.0/bin/plink
python: /opt/software/python/3.9.9/bin/python3
tmp_dir: /maps/projects/seqafrica/people/pls394/others/Marius/GT/tmp_dir
results_dir: results
rscript: /opt/software/R/4.2.2/bin/Rscript
